import 'package:uuid/uuid.dart';
import '../models/student.dart';
import '../models/parent.dart';
import '../models/menu_item.dart';
import '../services/student_service.dart';
import '../services/parent_service.dart';
import '../services/menu_service.dart';

/// Seed data utility to populate Firestore with realistic Loheca School canteen data
class SeedDataUtil {
  static const uuid = Uuid();
  
  final StudentService _studentService = StudentService();
  final ParentService _parentService = ParentService();
  final MenuService _menuService = MenuService();

  /// Seed all data
  Future<void> seedAll() async {
    await Future.wait([
      seedParents(),
      seedStudents(),
      seedMenuItems(),
    ]);
  }

  /// Seed realistic parent data
  /// 
  /// Note: This creates Parent documents only (not Firebase Auth accounts or users collection).
  /// For complete parent registration with Auth + users + parents, use RegistrationService.
  Future<void> seedParents() async {
    final parents = [
      Parent(
        userId: 'parent-001-maria-santos',
        balance: 500.00,
        phone: '+639171234567',
        address: '123 Santos Street, Manila',
        children: [], // Will be populated when students are linked
        createdAt: DateTime.now().subtract(const Duration(days: 60)),
        updatedAt: DateTime.now().subtract(const Duration(days: 60)),
      ),
      Parent(
        userId: 'parent-002-juan-delacruz',
        balance: 350.00,
        phone: '+639181234567',
        address: '456 Dela Cruz Avenue, Quezon City',
        children: [],
        createdAt: DateTime.now().subtract(const Duration(days: 55)),
        updatedAt: DateTime.now().subtract(const Duration(days: 55)),
      ),
      Parent(
        userId: 'parent-003-ana-reyes',
        balance: 425.00,
        phone: '+639191234567',
        address: '789 Reyes Road, Makati',
        children: [],
        createdAt: DateTime.now().subtract(const Duration(days: 50)),
        updatedAt: DateTime.now().subtract(const Duration(days: 50)),
      ),
      Parent(
        userId: 'parent-004-jose-garcia',
        balance: 275.00,
        phone: '+639201234567',
        address: '321 Garcia Boulevard, Pasig',
        children: [],
        createdAt: DateTime.now().subtract(const Duration(days: 45)),
        updatedAt: DateTime.now().subtract(const Duration(days: 45)),
      ),
    ];

    for (var parent in parents) {
      await _parentService.createParent(parent);
    }
    
    // Note: You should also create corresponding user documents in the users collection
    // For each parent above, create a user document like:
    // users/parent-001-maria-santos -> { uid, name: "Maria Santos", email, role: "parent", ... }
  }

  /// Seed realistic students (Nursery to Grade 6)
  Future<void> seedStudents() async {
    final students = [
      // Nursery students (3-4 years old)
      Student(
        id: uuid.v4(),
        firstName: 'Sofia',
        lastName: 'Santos',
        grade: 'Nursery',
        parentId: 'parent-001',
        allergies: 'Dairy',
        dietaryRestrictions: 'Lactose intolerant',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 120)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Miguel',
        lastName: 'Reyes',
        grade: 'Nursery',
        parentId: 'parent-002',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 115)),
      ),
      
      // Kinder students (5 years old)
      Student(
        id: uuid.v4(),
        firstName: 'Isabella',
        lastName: 'Garcia',
        grade: 'Kinder',
        parentId: 'parent-003',
        allergies: 'Peanuts',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 110)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Lucas',
        lastName: 'Dela Cruz',
        grade: 'Kinder',
        parentId: 'parent-004',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 105)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Mia',
        lastName: 'Santos',
        grade: 'Kinder',
        parentId: 'parent-001',
        dietaryRestrictions: 'Vegetarian',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 100)),
      ),

      // Grade 1 students (6 years old)
      Student(
        id: uuid.v4(),
        firstName: 'Daniel',
        lastName: 'Reyes',
        grade: 'Grade 1',
        parentId: 'parent-002',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 95)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Emma',
        lastName: 'Garcia',
        grade: 'Grade 1',
        parentId: 'parent-003',
        allergies: 'Shellfish',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 90)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Ethan',
        lastName: 'Dela Cruz',
        grade: 'Grade 1',
        parentId: 'parent-004',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 85)),
      ),

      // Grade 2 students (7 years old)
      Student(
        id: uuid.v4(),
        firstName: 'Sophia',
        lastName: 'Santos',
        grade: 'Grade 2',
        parentId: 'parent-001',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 80)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Noah',
        lastName: 'Reyes',
        grade: 'Grade 2',
        parentId: 'parent-002',
        allergies: 'Eggs',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 75)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Ava',
        lastName: 'Garcia',
        grade: 'Grade 2',
        parentId: 'parent-003',
        dietaryRestrictions: 'Halal',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 70)),
      ),

      // Grade 3 students (8 years old)
      Student(
        id: uuid.v4(),
        firstName: 'Liam',
        lastName: 'Dela Cruz',
        grade: 'Grade 3',
        parentId: 'parent-004',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 65)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Olivia',
        lastName: 'Santos',
        grade: 'Grade 3',
        parentId: 'parent-001',
        allergies: 'Tree Nuts',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 60)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Mason',
        lastName: 'Reyes',
        grade: 'Grade 3',
        parentId: 'parent-002',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 55)),
      ),

      // Grade 4 students (9 years old)
      Student(
        id: uuid.v4(),
        firstName: 'Charlotte',
        lastName: 'Garcia',
        grade: 'Grade 4',
        parentId: 'parent-003',
        dietaryRestrictions: 'Vegan',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 50)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Elijah',
        lastName: 'Dela Cruz',
        grade: 'Grade 4',
        parentId: 'parent-004',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 45)),
      ),

      // Grade 5 students (10 years old)
      Student(
        id: uuid.v4(),
        firstName: 'Amelia',
        lastName: 'Santos',
        grade: 'Grade 5',
        parentId: 'parent-001',
        allergies: 'Soy',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 40)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'James',
        lastName: 'Reyes',
        grade: 'Grade 5',
        parentId: 'parent-002',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 35)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Harper',
        lastName: 'Garcia',
        grade: 'Grade 5',
        parentId: 'parent-003',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
      ),

      // Grade 6 students (11-12 years old)
      Student(
        id: uuid.v4(),
        firstName: 'Benjamin',
        lastName: 'Dela Cruz',
        grade: 'Grade 6',
        parentId: 'parent-004',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 25)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Evelyn',
        lastName: 'Santos',
        grade: 'Grade 6',
        parentId: 'parent-001',
        allergies: 'Fish',
        dietaryRestrictions: 'Gluten-free',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
      ),
      Student(
        id: uuid.v4(),
        firstName: 'Alexander',
        lastName: 'Reyes',
        grade: 'Grade 6',
        parentId: 'parent-002',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
      ),
    ];

    for (var student in students) {
      await _studentService.addStudent(student);
    }
  }

  /// Seed realistic Filipino canteen menu items
  Future<void> seedMenuItems() async {
    final now = DateTime.now();
    
    final menuItems = [
      // ==================== SNACK (14 items) ====================
      MenuItem(
        id: uuid.v4(),
        name: 'Banana Cue',
        description: 'Deep-fried banana coated with caramelized sugar',
        price: 15.00,
        category: 'Snack',
        allergens: [],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 30,
        createdAt: now.subtract(const Duration(days: 10)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Turon',
        description: 'Fried spring roll with banana and jackfruit filling',
        price: 18.00,
        category: 'Snack',
        allergens: ['Wheat/Gluten'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 25,
        createdAt: now.subtract(const Duration(days: 9)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Pandesal with Cheese',
        description: 'Filipino bread roll filled with cheddar cheese',
        price: 12.00,
        category: 'Snack',
        allergens: ['Dairy', 'Wheat/Gluten', 'Eggs'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 40,
        createdAt: now.subtract(const Duration(days: 8)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Ensaymada',
        description: 'Sweet buttery pastry topped with cheese and sugar',
        price: 20.00,
        category: 'Snack',
        allergens: ['Dairy', 'Wheat/Gluten', 'Eggs'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 20,
        createdAt: now.subtract(const Duration(days: 7)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Hotdog Bun',
        description: 'Soft bun with Filipino-style hotdog',
        price: 25.00,
        category: 'Snack',
        allergens: ['Wheat/Gluten', 'Eggs', 'Soy'],
        isVegetarian: false,
        isVegan: false,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 35,
        createdAt: now.subtract(const Duration(days: 6)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Puto Cheese',
        description: 'Steamed rice cake topped with cheese',
        price: 10.00,
        category: 'Snack',
        allergens: ['Dairy', 'Eggs'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 30,
        createdAt: now.subtract(const Duration(days: 5)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Bicho-bicho',
        description: 'Crunchy twisted dough sprinkled with sugar',
        price: 8.00,
        category: 'Snack',
        allergens: ['Wheat/Gluten'],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 40,
        createdAt: now.subtract(const Duration(days: 4)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Cheese Sticks',
        description: 'Crispy fried cheese wrapped in lumpia wrapper',
        price: 12.00,
        category: 'Snack',
        allergens: ['Dairy', 'Wheat/Gluten'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 30,
        createdAt: now.subtract(const Duration(days: 3)),
      ),

      // ==================== LUNCH - MONDAY (3 items) ====================
      MenuItem(
        id: uuid.v4(),
        name: 'Chicken Adobo',
        description: 'Savory Filipino chicken stew with soy sauce and vinegar',
        price: 45.00,
        category: 'Lunch',
        allergens: ['Soy'],
        isVegetarian: false,
        isVegan: false,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 50,
        createdAt: now.subtract(const Duration(days: 15)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Steamed Rice',
        description: 'Fluffy white rice',
        price: 10.00,
        category: 'Lunch',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 100,
        createdAt: now.subtract(const Duration(days: 15)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Mixed Vegetables',
        description: 'Sautéed carrots, cabbage, and green beans',
        price: 15.00,
        category: 'Lunch',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 40,
        createdAt: now.subtract(const Duration(days: 15)),
      ),

      // ==================== LUNCH - TUESDAY (3 items) ====================
      MenuItem(
        id: uuid.v4(),
        name: 'Pork Giniling',
        description: 'Filipino ground pork with potatoes and carrots',
        price: 40.00,
        category: 'Lunch',
        allergens: ['Soy'],
        isVegetarian: false,
        isVegan: false,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 45,
        createdAt: now.subtract(const Duration(days: 14)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Steamed Rice',
        description: 'Fluffy white rice',
        price: 10.00,
        category: 'Lunch',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 100,
        createdAt: now.subtract(const Duration(days: 14)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Fresh Fruit Salad',
        description: 'Mixed tropical fruits with cream',
        price: 20.00,
        category: 'Lunch',
        allergens: ['Dairy'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 30,
        createdAt: now.subtract(const Duration(days: 14)),
      ),

      // ==================== LUNCH - WEDNESDAY (3 items) ====================
      MenuItem(
        id: uuid.v4(),
        name: 'Fish Fillet',
        description: 'Breaded and fried fish fillet',
        price: 50.00,
        category: 'Lunch',
        allergens: ['Fish', 'Wheat/Gluten', 'Eggs'],
        isVegetarian: false,
        isVegan: false,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 40,
        createdAt: now.subtract(const Duration(days: 13)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Steamed Rice',
        description: 'Fluffy white rice',
        price: 10.00,
        category: 'Lunch',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 100,
        createdAt: now.subtract(const Duration(days: 13)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Corn Kernels',
        description: 'Buttered sweet corn',
        price: 12.00,
        category: 'Lunch',
        allergens: ['Dairy'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 35,
        createdAt: now.subtract(const Duration(days: 13)),
      ),

      // ==================== LUNCH - THURSDAY (3 items) ====================
      MenuItem(
        id: uuid.v4(),
        name: 'Chicken Nuggets',
        description: 'Crispy fried chicken nuggets',
        price: 45.00,
        category: 'Lunch',
        allergens: ['Wheat/Gluten', 'Eggs', 'Soy'],
        isVegetarian: false,
        isVegan: false,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 50,
        createdAt: now.subtract(const Duration(days: 12)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Steamed Rice',
        description: 'Fluffy white rice',
        price: 10.00,
        category: 'Lunch',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 100,
        createdAt: now.subtract(const Duration(days: 12)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Garlic Green Beans',
        description: 'Sautéed green beans with garlic',
        price: 15.00,
        category: 'Lunch',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 40,
        createdAt: now.subtract(const Duration(days: 12)),
      ),

      // ==================== LUNCH - FRIDAY (3 items) ====================
      MenuItem(
        id: uuid.v4(),
        name: 'Beef Tapa',
        description: 'Sweet and savory marinated beef',
        price: 55.00,
        category: 'Lunch',
        allergens: ['Soy'],
        isVegetarian: false,
        isVegan: false,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 40,
        createdAt: now.subtract(const Duration(days: 11)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Garlic Fried Rice',
        description: 'Fried rice with garlic',
        price: 15.00,
        category: 'Lunch',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 100,
        createdAt: now.subtract(const Duration(days: 11)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Atchara',
        description: 'Pickled green papaya relish',
        price: 10.00,
        category: 'Lunch',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 50,
        createdAt: now.subtract(const Duration(days: 11)),
      ),

      // Additional Snack Items
      MenuItem(
        id: uuid.v4(),
        name: 'Spaghetti',
        description: 'Filipino-style sweet spaghetti with hotdog',
        price: 30.00,
        category: 'Snack',
        allergens: ['Wheat/Gluten', 'Dairy'],
        isVegetarian: false,
        isVegan: false,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 30,
        createdAt: now.subtract(const Duration(days: 10)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Palabok',
        description: 'Rice noodles with shrimp sauce and toppings',
        price: 35.00,
        category: 'Snack',
        allergens: ['Shellfish', 'Eggs'],
        isVegetarian: false,
        isVegan: false,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 25,
        createdAt: now.subtract(const Duration(days: 9)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Puto Bumbong',
        description: 'Purple rice cake topped with butter and coconut',
        price: 15.00,
        category: 'Snack',
        allergens: ['Dairy'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 30,
        createdAt: now.subtract(const Duration(days: 8)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Banana Muffin',
        description: 'Moist banana muffin',
        price: 18.00,
        category: 'Snack',
        allergens: ['Wheat/Gluten', 'Eggs', 'Dairy'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 25,
        createdAt: now.subtract(const Duration(days: 7)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Macaroni Salad',
        description: 'Creamy macaroni pasta salad',
        price: 22.00,
        category: 'Snack',
        allergens: ['Wheat/Gluten', 'Dairy', 'Eggs'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: false,
        isAvailable: true,
        stockQuantity: 20,
        createdAt: now.subtract(const Duration(days: 6)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'French Fries',
        description: 'Crispy golden french fries',
        price: 25.00,
        category: 'Snack',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 40,
        createdAt: now.subtract(const Duration(days: 5)),
      ),

      // ==================== DRINKS (6 items) ====================
      MenuItem(
        id: uuid.v4(),
        name: 'Orange Juice',
        description: 'Freshly squeezed orange juice',
        price: 20.00,
        category: 'Drinks',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 50,
        createdAt: now.subtract(const Duration(days: 10)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Mango Juice',
        description: 'Sweet mango juice',
        price: 20.00,
        category: 'Drinks',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 50,
        createdAt: now.subtract(const Duration(days: 9)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Chocolate Milk',
        description: 'Cold chocolate flavored milk',
        price: 25.00,
        category: 'Drinks',
        allergens: ['Dairy'],
        isVegetarian: true,
        isVegan: false,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 40,
        createdAt: now.subtract(const Duration(days: 8)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Bottled Water',
        description: 'Purified drinking water',
        price: 12.00,
        category: 'Drinks',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 100,
        createdAt: now.subtract(const Duration(days: 7)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Buko Juice',
        description: 'Fresh coconut water',
        price: 18.00,
        category: 'Drinks',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 30,
        createdAt: now.subtract(const Duration(days: 6)),
      ),
      MenuItem(
        id: uuid.v4(),
        name: 'Gulaman',
        description: 'Sweet gelatin drink',
        price: 15.00,
        category: 'Drinks',
        allergens: [],
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isAvailable: true,
        stockQuantity: 40,
        createdAt: now.subtract(const Duration(days: 5)),
      ),
    ];

    for (var item in menuItems) {
      await _menuService.createMenuItem(item);
    }
  }

  /// Seed orders (placeholder for future implementation)
  Future<void> seedOrders() async {
    // TODO: Implement order seeding when order model is ready
  }

  /// Seed topups (placeholder for future implementation)
  Future<void> seedTopups() async {
    // TODO: Implement topup seeding when topup model is ready
  }
}



